### ISSUE TITLE
Make setup_local_grafana_docker.sh script idempotent

### ISSUE THREAD

**Issue by doronbl** [aws-samples/aws-iot-twinmaker-samples#19]
When setting up the environment to be used for long term usage such as demo, user will probably encounter the grafana docker to be stopped or terminated. The easiest way to re-run the container is by re-running setup_local_grafana_docker.sh which yelled some errors on file deletion permissions.
This lower the trust user have on the stability of the environment.
Suggesting to either make the script idempotent.

**Comment by johnnyw-aws** [comment]
Hi @doronbl thanks for your suggestion! We've since been recommending customers to use Amazon Managed Grafana instead of self-hosted, which simplifies much of the environment management. The current script is able to run idempotently but may require to be run with a user that has the file deletion permissions you mentioned.

We haven't seen any re-occurrences of the issue you described so we'll close this issue and re-open based on new customer feedback. Please feel free to re-open if still have any concerns, thanks!
